# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./disk-config.nix
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.binfmt.emulatedSystems = ["aarch64-linux"];

  fileSystems."/var/lib/nextcloud" = {
    device = "/media/nextcloud";
    options = [
      "bind"
    ];
  };
  fileSystems."/var/lib/docker" = {
    device = "/media/docker";
    options = [
      "bind"
    ];
  };

  fileSystems."/home".neededForBoot = true;

  # fileSystems."/" = {
  #   device = "/dev/disk/by-uuid/8f805d1b-a469-4db8-9ee1-b98ea220714a";
  #   fsType = "ext4";
  # };
  #
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/D840-A590";
  #   fsType = "vfat";
  #   options = ["fmask=0022" "dmask=0022"];
  # };
  #
  # fileSystems."/media" = {
  #   device = "/dev/disk/by-uuid/cad22fc7-08d2-4650-8d5e-a101e3fd1bd1";
  #   fsType = "ext4";
  # };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
