name: Build and Cache

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build ${{ matrix.host }}
    runs-on: nix
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: ryu
            flake: nixosConfigurations.ryu.config.system.build.toplevel
          - host: tako
            flake: nixosConfigurations.tako.config.system.build.toplevel
          - host: tsuba
            flake: nixosConfigurations.tsuba.config.system.build.toplevel
    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ matrix.host }}
        run: nix build .#${{ matrix.flake }} --no-link --print-out-paths --show-trace

  build-darwin:
    name: Build ${{ matrix.host }}
    runs-on: nix-darwin
    env:
      CACHE_HOST: ssh-ng://gitea-runner@tako.darksailor.dev
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: kuro
            flake: darwinConfigurations.kuro.system
          - host: shiro
            flake: darwinConfigurations.shiro.system
    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ matrix.host }}
        run: |
          out=$(nix build .#${{ matrix.flake }} --no-link --print-out-paths --show-trace)
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then nix copy --to "$CACHE_HOST" "$out" -j 4; fi
