#!/bin/sh

export SXHKD_SHELL="/bin/sh"
sxhkd &
xsetroot -cursor_name left_ptr &

# bspc monitor eDP1  -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI1 -d XI XII XIII XIV XV XVI XVII XVIII XIX XX
bspc monitor HDMI-2 -d I II III IV V VI VII VIII IX X


bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_width         0

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a qutebrowser desktop='^3'
bspc rule -a Steam state=tiled
bspc rule -a steam_app_230410 desktop='^4' state=fullscreen
bspc rule -a vlc desktop='^5'
bspc rule -a mpv desktop='^5'
bspc rule -a spotify desktop='^10'

# To help with the java applications
#wmname LG3D
#not anymore
export _JAVA_AWT_WM_NONREPARENTING=1

# So that sxhkd uses sh instead of zsh or bash
set -U SXHKD_SHELL sh
