#!/bin/sh

setxkbmap -option "ctrl:nocaps" 
picom --config ~/.config/picom/picom.conf &
xrandr --output DP-4 --mode 2560x1440 --refresh 170 --pos 1440x538 --rotate normal --output DP-2 --mode 2560x1440 --pos 0x0 --rotate left --refresh 170
# libinput-gestures &
#discord --start-minimized &
xwallpaper --zoom ~/.local/share/dotfiles/images/wallpaper.jpg &
export _JAVA_AWT_WM_NONREPARENTING=1
conky &
unclutter &
# twmnd &
# xf86keys -d &
aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec bspwm
