name: Flake checker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nix_check:
      name: Build Nix targets
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Check Nix flake inputs
          uses: DeterminateSystems/flake-checker-action@main
