wifi_ssid: ENC[AES256_GCM,data:NnVQYmNcUYJaFjI=,iv:BnLy0ps0NXEQPI1mo89Ts904EdjYl/Aoam37Lg6S4i4=,tag:1vgHdIJaUf1NnkMEIDoJBg==,type:str]
wifi_password: ENC[AES256_GCM,data:cKTVPyePQEQ=,iv:kAnTlamPYQeLmuIkLh5bR35GVwtHfelBYuOv3lb8lkM=,tag:rpv/8TIZTlhxqG9Rtm7phw==,type:str]
ota_password: ENC[AES256_GCM,data:1RPEM6+pmnvI6BjIEzouwfnLGLfetA==,iv:tY5Vp756nRVIyGhFlE+xc953HNzIlmn1XH57XYGIW1o=,tag:RC7pCj3Z0513DzvVIzsepg==,type:str]
reterminal_e1002_enc_key: ENC[AES256_GCM,data:w/8ioxMZgx28x2DPEUBNXzQETYWAIuxKJYNJreJ88V0RYzOQvZ7GVPhDSLY=,iv:dxFcd7ds5KFiIPi4l+8SS+O1tqOG7BxSD/ekzmiUI94=,tag:GCVF4IAEuFtSQghA2Zyx8g==,type:str]
sops:
    age:
        - recipient: age1pw7kluxp7872c63ne4jecq75glj060jkmqwzkk6esatuyck9egfswufdpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL3N2WG43aGpNeXBrZDd5
            cDdOZkRiaWhjWEtFczVzc1Y1M2QxTU1ra1hrCjFydUg2QzNzK0owTHFKeTlUVzZ6
            ZlRxdTBUUHorWHczY0VxdGd3UVJ3cnMKLS0tIGdWRS9QdnFFdWYyOG5LQnZjV0dq
            UGV0VDhwOTJwNXRUYnBzS2F6MUhDdHMKo89gNR1JQfHM9zsH/bcf/fZts8jWu7FC
            rqVMqcdCaieT/mzrFZ8V5DUzjthnErhVS7nN3tZAxPhLgHPLwNcYkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T20:03:57Z"
    mac: ENC[AES256_GCM,data:OVuclHg0wNAsE8IOKPScOXmoWIq1bfV8l36mm+SI3swue5doV+JRjlKUEC3CaxZYq/de61xfP05y1bI1Oc3z6ZQLBfVfrRwtWMsi+PjPGFFGRc/O/oM+pX13XitqnvIHigRbH6sdu32VqvpGH8ywoOh00yPw0uFhnoTbuDzZcSM=,iv:Wwv2EKmb4ejcJ8C45w9H1rhmO79tcOh1WDIpdjEFRVo=,tag:JaQuDrOAR9qsP+oS/ot97w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
