wifi_ssid: ENC[AES256_GCM,data:NnVQYmNcUYJaFjI=,iv:BnLy0ps0NXEQPI1mo89Ts904EdjYl/Aoam37Lg6S4i4=,tag:1vgHdIJaUf1NnkMEIDoJBg==,type:str]
wifi_password: ENC[AES256_GCM,data:cKTVPyePQEQ=,iv:kAnTlamPYQeLmuIkLh5bR35GVwtHfelBYuOv3lb8lkM=,tag:rpv/8TIZTlhxqG9Rtm7phw==,type:str]
ota_password: ENC[AES256_GCM,data:1RPEM6+pmnvI6BjIEzouwfnLGLfetA==,iv:tY5Vp756nRVIyGhFlE+xc953HNzIlmn1XH57XYGIW1o=,tag:RC7pCj3Z0513DzvVIzsepg==,type:str]
sops:
    age:
        - recipient: age1pw7kluxp7872c63ne4jecq75glj060jkmqwzkk6esatuyck9egfswufdpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL3N2WG43aGpNeXBrZDd5
            cDdOZkRiaWhjWEtFczVzc1Y1M2QxTU1ra1hrCjFydUg2QzNzK0owTHFKeTlUVzZ6
            ZlRxdTBUUHorWHczY0VxdGd3UVJ3cnMKLS0tIGdWRS9QdnFFdWYyOG5LQnZjV0dq
            UGV0VDhwOTJwNXRUYnBzS2F6MUhDdHMKo89gNR1JQfHM9zsH/bcf/fZts8jWu7FC
            rqVMqcdCaieT/mzrFZ8V5DUzjthnErhVS7nN3tZAxPhLgHPLwNcYkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T19:27:19Z"
    mac: ENC[AES256_GCM,data:RGk0pOI9pcem0WOhfacFaFUyjl6OaqCiKt4epVUcql/Ml0Uve2Wgm1bVPkOQD6EWwDNjAhxj4CZRtPGaZrg1TEQnLkMjGmbZ6JSo/TpvJD9v/JRH881hBwx4umR7JOynp3KcIJgYW8h+he8cQ2MCOtJIEh4Z6CbJ88rKwothFSo=,iv:ZiKNUzJ7s52/9rVC5MFeB4QvObIQf7BLzVsD3KxNkrM=,tag:f8ul4gstfYL7HgvhW7OlKg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
